config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  get "/", to: "users#index"
  get "/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  get "/idea/new", to: "blogs#new", as: "new_idea"
  post "/blogs", to: "blogs#create"
  get "/ideas", to: "blogs#index", as: "user_ideas"
  get "/ideas/:id", to: "blogs#show", as: "idea"
  get "/ideas/:id/edit", to: "blogs#edit", as: "edit_blog"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :blogs

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.create(blog_params)
    current_user.blogs << @blog
    redirect_to current_user
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to user_ideas_path
    else
      render 'edit'
    end
  end



  private
  def blog_params
    params.require(:blog).permit(:title, :content, :user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Successfully logged in"
      redirect_to @user
    else
      flash[:error] = "Incorrect email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end

  private
  def user_params
    user_params = params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    login(@user)
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  # def edit
  #   @user = User.find(params[:id])
  # end
  #
  # def update
  #   @user = User.find(params[:id])
  #   if @user.update(user_params)
  #     redirect_to @user
  #   else
  #     render 'edit'
  #   end
  # end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  def logout
    @current_user = session[:user_id] = nil
  end
  def require_login
    if current_user == nil
      redirect_to new_session_path
    end
  end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/edit.html.erb
<div> <%= @blog.title %> </div>
<% form_for @blog do |f| %>
  <div>
    <%= f.text_field :title, placeholder: f.title %>
  </div>
  <div>
    <%= f.text_field :content, placeholder: f.content %>
  </div>
  <%= f.submit %>
<% end %>

app/views/blogs/index.html.erb
<div class="ideas container">
  <div id="ideas-page" class="row">
    <div class="col-sm-12">
        <h4> Your ideas </h4>
        <%= link_to "New Idea", new_idea_path %>
        <div class="row">
          <% current_user.blogs().each do |b|%>
            <div class="card-col col-sm-3">
              <div class="card idea-card">
                <div class="card-body">
                  <h4 class="card-title"><%= b.title %> </h4>
                  <p class="card-text"><%= b.content %> </p>
                  <%= link_to "Edit Idea", edit_blog_path(b.id) %>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
    <div class="col-sm-4">

    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container new-idea-container">
  <div class="row">
    <div class="idea-form col-sm-12">
      <h3> New Idea</h3>
      <%= form_for @blog do |f| %>
        <div>
          <%= f.text_field :title, placeholder: "Title" %>
        </div>
        <div>
          <%= f.text_area :content, size: "18x8", placeholder: "Write here!" %>
        </div>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<h1>Blogs#show</h1>
<p>Find me in app/views/blogs/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="navbar-default navbar-bottom">
  <div class="container clearfix">
    <p class="copyright">Copyright 2017</p>
    <p class="author">By creativesnopeks</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <nav id="main-nav" class="clearfix navbar navbar-dark collapse navbar-collapse">
    <div>
      <p class="header-brand">Innovately</p>
    </div>
    <ul class="nav navbar-nav">
      <% if current_user %>
        <li><%= link_to "Ideas", user_ideas_path %>
        <li><%= link_to "Profile", current_user %>
        <li><%= link_to "Logout", "/logout" %>
      <% else %>
        <li><%= link_to "Login", "/login" %></li>
        <li><%= link_to "Signup", "/new"%></li>
      <% end %>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InnovatelyRuby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="jumbotron">
  <h1>Innovately</h1>
  <p>Bring your ideas to life</p>
  <p><a class="btn btn-primary btn-md" href="/new" role="button">Sign up</a></p>
</div>
<div class="row">
  <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="service-item first-service">
          <div class="icon"></div>
          <span class="glyphicon glyphicon-plus"></span>
          <h4>Track Ideas</h4>
          <p>Save your most innovative ideas to this "digital notebook", get a full spectrum of feedback from other thinkers and makers!</p>
      </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="service-item second-service">
          <div class="icon"></div>
          <span class="glyphicon glyphicon-ok"></span>
          <h4>Dream Big</h4>
          <p>Try and spice it up. Make a plan for pursuing your greatest ideas. Get help from other users and achieve your goals!</p>
      </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="service-item third-service">
          <div class="icon"></div>
          <span class="glyphicon glyphicon-search"></span>
          <h4>Browse Others</h4>
          <p>Don't have an idea, but want to see others? Scroll through the latest ideas, give feedback, and work with like-minded people.</p>
      </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="service-item fourth-service">
          <div class="icon"></div>
          <span class="glyphicon glyphicon-heart"></span>
          <h4>Collaberate</h4>
          <p>Love the idea and want in? Click on the collaberate button next to the post to contact the owner of the post.</p>
      </div>
  </div>
</div>
<div class="container hook">
  <div class="row">
    <div class="col-md-12">

      <p>Track and share your ideas! Collaborate with others to bring your ideas to life.</p>
    </div>
  </div>
</div>
<div id="fun-facts">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="fact-item">
                    <div class="counter" data-count="2">300</div>
                    <span>Regular Visitors</span>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="fact-item">
                    <div class="counter" data-count="0">459</div>
                    <span>Finished Projects</span>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="fact-item">
                    <div class="counter" data-count="0">2102</div>
                    <span>Great Ideas</span>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container signup-container">
  <div class="row">
    <div class="col-md-12 signup-form">
      <h1> Sign up</h1>
      <%= form_for @user do |f| %>
        <div>
          <%= f.text_field :name, placeholder: "Name" %>
        </div>
        <div>
          <%= f.text_field :email, placeholder: "Email" %>
        </div>
        <div>
          <%= f.password_field :password, placeholder: "Password" %>
        </div>
        <%= f.submit "Sign Up" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container profile-container">
  <div id="profile" class="row">
    <h3>Your profile</h3>
    <div class="col-sm-4">
      <p> Hi, <%= current_user.name %>!</p>
      <p> Your email: <%= current_user.email %> </p>
    </div>
    <div class="col-sm-4">
      <p> You have logged <%= current_user.blogs().length %> ideas!</p>
      <div class="card profile-card" style="width: 20rem;">
        <ul class="list-group list-group-flush">
          <% current_user.blogs().each do |b| %>
          <li class="list-group-item"><%=b.title%> </li>
          <% end %>
        </ul>
        <p><%= link_to "Create New Idea", new_idea_path %></p>
      </div>
    </div>
    <div class="col-sm-4">
      <p> Favorite Ideas </p>
      <div class="card" style="width: 20rem;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Fav idea 1</li>
          <li class="list-group-item">Fav idea 2</li>
          <li class="list-group-item">Fav idea 3</li>
        </ul>
      </div>
    </div>
  </div>
</div>